# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ahshoe/Desktop/camCal/core/main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 700)
        MainWindow.setMinimumSize(QtCore.QSize(600, 700))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MU = QtWidgets.QRadioButton(self.centralWidget)
        self.MU.setChecked(True)
        self.MU.setObjectName("MU")
        self.horizontalLayout.addWidget(self.MU)
        self.IU = QtWidgets.QRadioButton(self.centralWidget)
        self.IU.setObjectName("IU")
        self.horizontalLayout.addWidget(self.IU)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.Har_H = QtWidgets.QVBoxLayout()
        self.Har_H.setObjectName("Har_H")
        self.verticalLayout_17.addLayout(self.Har_H)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Har_velocity = QtWidgets.QVBoxLayout()
        self.Har_velocity.setObjectName("Har_velocity")
        self.verticalLayout_15.addLayout(self.Har_velocity)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.Har_acceleration = QtWidgets.QVBoxLayout()
        self.Har_acceleration.setObjectName("Har_acceleration")
        self.verticalLayout_19.addLayout(self.Har_acceleration)
        self.verticalLayout_2.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Har_jump = QtWidgets.QVBoxLayout()
        self.Har_jump.setObjectName("Har_jump")
        self.verticalLayout_18.addLayout(self.Har_jump)
        self.verticalLayout_2.addWidget(self.groupBox_12)
        self.HarThita = QtWidgets.QSlider(self.tab_2)
        self.HarThita.setMaximum(360)
        self.HarThita.setProperty("value", 360)
        self.HarThita.setOrientation(QtCore.Qt.Horizontal)
        self.HarThita.setObjectName("HarThita")
        self.verticalLayout_2.addWidget(self.HarThita)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_17 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.Cy_H = QtWidgets.QVBoxLayout()
        self.Cy_H.setObjectName("Cy_H")
        self.verticalLayout_24.addLayout(self.Cy_H)
        self.verticalLayout_3.addWidget(self.groupBox_17)
        self.groupBox_18 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.Cy_velocity = QtWidgets.QVBoxLayout()
        self.Cy_velocity.setObjectName("Cy_velocity")
        self.verticalLayout_25.addLayout(self.Cy_velocity)
        self.verticalLayout_3.addWidget(self.groupBox_18)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.Cy_acceleration = QtWidgets.QVBoxLayout()
        self.Cy_acceleration.setObjectName("Cy_acceleration")
        self.verticalLayout_26.addLayout(self.Cy_acceleration)
        self.verticalLayout_3.addWidget(self.groupBox_19)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.Cy_jump = QtWidgets.QVBoxLayout()
        self.Cy_jump.setObjectName("Cy_jump")
        self.verticalLayout_27.addLayout(self.Cy_jump)
        self.verticalLayout_3.addWidget(self.groupBox_20)
        self.CyThita = QtWidgets.QSlider(self.tab_3)
        self.CyThita.setMaximum(360)
        self.CyThita.setProperty("value", 360)
        self.CyThita.setOrientation(QtCore.Qt.Horizontal)
        self.CyThita.setObjectName("CyThita")
        self.verticalLayout_3.addWidget(self.CyThita)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cam Shaft"))
        self.MU.setText(_translate("MainWindow", "Metric Units "))
        self.IU.setText(_translate("MainWindow", "Imperial Units"))
        self.groupBox_9.setTitle(_translate("MainWindow", "ΔR"))
        self.groupBox_10.setTitle(_translate("MainWindow", "velocity"))
        self.groupBox_11.setTitle(_translate("MainWindow", "acceleration"))
        self.groupBox_12.setTitle(_translate("MainWindow", "jerk"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Harmonic Motion"))
        self.groupBox_17.setTitle(_translate("MainWindow", "ΔR"))
        self.groupBox_18.setTitle(_translate("MainWindow", "velocity"))
        self.groupBox_19.setTitle(_translate("MainWindow", "acceleration"))
        self.groupBox_20.setTitle(_translate("MainWindow", "jerk"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Cycloidal motion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

